# Generated by Django 3.2 on 2021-05-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_auto_20210405_2012"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="description",
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name="account",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
