# Generated by Django 3.2 on 2021-05-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_auto_20210504_1954"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="isEnabled",
        ),
        migrations.AlterField(
            model_name="account",
            name="type",
            field=models.CharField(
                choices=[
                    ("account", "Account"),
                    ("savings", "Savings"),
                    ("investment", "Investments"),
                    ("other", "Others"),
                ],
                default="account",
                max_length=20,
            ),
        ),
    ]
