# Generated by Django 3.1.7 on 2021-04-07 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_transaction_created"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ("-created",)},
        ),
    ]
