# Generated by Django 3.2 on 2021-05-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20210504_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
