# Generated by Django 3.2 on 2021-05-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_alter_subcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='isIncome',
            field=models.BooleanField(default=False),
        ),
    ]
